name: ci
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        run: |
          npm ci || npm i
      - name: Lint
        run: |
          npx eslint . || echo "eslint missing; skipping"
      - name: Test
        run: |
          npm test --if-present || echo "no tests; skipping"
      - name: Build
        run: |
          npm run build --if-present || echo "no build step; skipping"
      - name: Smoke (health checks)
        run: |
          if [ -f "./tools/smoke.sh" ]; then bash ./tools/smoke.sh; else echo "no smoke script; skipping"; fi
