name: pages
on: { push: { branches: [main] } }
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { pages: write, id-token: write }
    steps:
      - uses: actions/checkout@v4
      - name: Build docs site
        run: |
          mkdir -p public && cp -r docs/site public/
      - uses: actions/upload-pages-artifact@v3
        with: { path: 'public' }
      - uses: actions/deploy-pages@v4
