name: secrets-watch
on:
  schedule: [{ cron: "17 9 * * *" }]
  workflow_dispatch: {}
jobs:
  check:
    runs-on: ubuntu-latest
    permissions: { contents: write, issues: write }
    steps:
      - name: Open checklist to verify secrets (placeholders replaced)
        uses: actions/github-script@v7
        with:
          script: |
            const keys = [
              'APP_ENV','LOG_LEVEL','JWT_SECRET','ENCRYPTION_KEY_32B',
              'TIKTOK_APP_ID','TIKTOK_APP_SECRET','TIKTOK_ADS_ACCESS_TOKEN','TIKTOK_REFRESH_TOKEN','TIKTOK_AD_ACCOUNT_ID','TIKTOK_PIXEL_ID',
              'META_APP_ID','META_APP_SECRET','META_SYSTEM_USER_TOKEN','META_AD_ACCOUNT_ID','META_PIXEL_ID','META_PAGE_ID','IG_BUSINESS_ACCOUNT_ID',
              'KLAVIYO_PUBLIC_KEY','KLAVIYO_PRIVATE_KEY','ELEVENLABS_API_KEY','RESEND_API_KEY',
              'GOOGLE_SHEETS_DB_SPREADSHEET_ID','GOOGLE_SERVICE_ACCOUNT_JSON_BASE64',
              'AWS_ACCESS_KEY_ID','AWS_SECRET_ACCESS_KEY','AWS_REGION','S3_BUCKET',
              'GCP_PROJECT_ID','GCS_BUCKET','GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64',
              'SENTRY_DSN','POSTHOG_PROJECT_API_KEY','AMPLITUDE_API_KEY','NETLIFY_AUTH_TOKEN','NETLIFY_SITE_ID','VERCEL_TOKEN','VERCEL_ORG_ID','VERCEL_PROJECT_ID',
              'SHOPIFY_API_KEY','SHOPIFY_API_SECRET','SHOPIFY_SCOPES','SHOPIFY_APP_URL','SHOPIFY_WEBHOOK_SECRET','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET'
            ];
            const body = "Replace <TODO> with live values:\n\n" + keys.map(k=>`- [ ] ${k}`).join('\n');
            const title = `Secrets audit checklist (${new Date().toISOString().slice(0,10)})`;
            await github.rest.issues.create({ owner: context.repo.owner, repo: context.repo.repo, title, body });
