name: spend-pacing-hourly
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: node analytics/spend_pacing.mjs || true
      - uses: actions/upload-artifact@v4
        with: { name: spend-pacing, path: analytics/spend_pacing.json }
